version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean:latest'
    ports:
      - '${JENKINS_HTTP_PORT}:8080'
      - '${JENKINS_HTTPS_PORT}:8443'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
    environment:
      - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=8443'
volumes:
  jenkins_data:
    driver: local